# Generated by Django 4.1.2 on 2022-10-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Osoby', '0007_alter_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko']},
        ),
        migrations.RemoveField(
            model_name='osoba',
            name='miesiac_urodzenia',
        ),
    ]
