# Generated by Django 4.1.2 on 2022-10-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Osoby', '0008_alter_osoba_options_remove_osoba_miesiac_urodzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='miesiac_urodzenia',
            field=models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default=6, max_length=2),
        ),
    ]
