# Generated by Django 4.1.3 on 2022-12-01 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wklejki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('kategoria', models.IntegerField(choices=[(1, 'Zwykły tekst'), (2, 'HTML'), (3, 'CSS'), (4, 'PHP'), (5, 'PYTHON'), (6, 'Ruby'), (7, 'C'), (8, 'C++'), (9, 'Go'), (10, 'Latex')])),
                ('tekst', models.CharField(blank=True, max_length=2137, null=True)),
                ('lajki', models.IntegerField()),
                ('wlasciciel_wklejki', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
