# Generated by Django 4.1.3 on 2022-12-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0002_alter_wklejki_tekst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wklejki',
            name='lajki',
            field=models.IntegerField(default=0),
        ),
    ]
