# Generated by Django 4.1.2 on 2022-12-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0003_alter_wklejki_lajki'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wklejki',
            options={'verbose_name': 'Wklejkii', 'verbose_name_plural': 'Wklejkiii'},
        ),
        migrations.AddIndex(
            model_name='wklejki',
            index=models.Index(fields=['kategoria'], name='kategoria_index'),
        ),
        migrations.AlterModelTable(
            name='wklejki',
            table='wklejki',
        ),
    ]
