# Generated by Django 4.1.3 on 2022-12-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0004_alter_wklejki_options_wklejki_kategoria_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wklejki',
            options={'verbose_name': 'Wklejki', 'verbose_name_plural': 'Wklejki'},
        ),
    ]
