# Generated by Django 4.1.3 on 2022-12-05 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wklejki', '0005_alter_wklejki_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wklejki',
            name='wlasciciel_wklejki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
