# Generated by Django 4.1.3 on 2022-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wklejki', '0006_alter_wklejki_wlasciciel_wklejki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wklejki',
            name='kategoria',
            field=models.CharField(choices=[('Zwykły tekst', 'Zwykły tekst'), ('html', 'HTML'), ('CSS', 'CSS'), ('PHP', 'PHP'), ('PYTHON', 'PYTHON'), ('Ruby', 'Ruby'), ('C', 'C'), ('C++', 'C++'), ('Go', 'Go'), ('Latex', 'Latex')], max_length=255),
        ),
    ]
