# Generated by Django 4.1.2 on 2022-10-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pastes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pastes',
            table='pastes',
        ),
    ]
